[build-system]
requires = ["setuptools>=42", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "TotalPear"
requires-python = ">=3.8"
dynamic = ["version"]
dependencies = []
readme = "README.md"
license = {file = "LICENSE.txt"}

